### ISSUE TITLE
LFW processing

### ISSUE THREAD

**Issue by jakezhaojb** [skaae/torch-gan#1]
Hi,

I can't make your create_dataset.py to work. One sanity check failing: `np.array(self.imgs.tolist().getdata()).sum()` seems to be zero.

The actual error I got is:

``` py
Traceback (most recent call last):
  File "create_datasets.py", line 38, in <module>
    x = create_lfw()
  File "create_datasets.py", line 27, in create_lfw
    imgs = lfw_imgs(alignment='deepfunneled', size=64, crop=50)
  File "create_datasets.py", line 19, in lfw_imgs
    img = img[crop:-crop, crop:-crop]
IndexError: too many indices for array
```

Thank you,
Jake

**Comment by skaae** [comment]
Hi jake,
I just tried with a fresh repo and it works fine for me. Are you sure the files are downloaded correctly?

**Comment by jakezhaojb** [comment]
Hi,

I think I downloaded it right. Can you tell me the version you are using for `python` and `PIL`?

**Comment by jakezhaojb** [comment]
I think the problem is originated from #L16 of create_dataset.py in which I got an numpy.array carrying a number of PIL image handlers, and #L19 won't allow this object array to be cropped. 

So that I suspect if there is a version discrepancy

**Comment by andersbll** [comment]
Hi there! Make sure you are using Pillow rather than PIL.

The python script works using a recent version of Anaconda Linux with Pillow 3.

**Comment by jakezhaojb** [comment]
Thanks @andersbll 
That was exactly the problem!
